version: "3.1"

services:
  db:
    image: mariadb:10.6
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
  site:
    depends_on:
      - db
    volumes:
      - html_folder:/var/www/html
      - ./my-theme:/var/www/html/wp-content/themes/my-theme
      - ./my-plugin:/var/www/html/wp-content/plugins/my-plugin
    image: php-local:local
    restart: always
    ports:
      - 8084:80
    environment:
      PMA_HOST: db
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
volumes:
  db:
  html_folder:
